### ISSUE TITLE
Image resize like done on ep_copy_paste_images

### ISSUE THREAD

**Issue by Oremountainflorian** [citizenos/ep_image_upload#10]
Hey out there, 

have you already considered providing the option to resize images as @JohnMcLear did on ep_copy_paste_images? 

Here are some infos about that

https://github.com/JohnMcLear/ep_previewimages/issues/14#issuecomment-94252258

Thank you very much for your engagement! Best wishes, Flo

**Comment by Oremountainflorian** [comment]
**Update** On Firefox/Chrome (at least with Windows) it's possible to resize images by going to the respective line hitting tab (smaller) and shift+tab (larger)

**Comment by tiblu** [comment]
Yes, we have talked about it, but our organization has 1.5 developers thus it will probably be at the bottom of the priority list.

I will add this to our prioritization.

Also, we welcome pull requests!

**Comment by loorm** [comment]
Triage 23. @Oremountainflorian ep_copy_paste_images implementation is styles-only. However, in Citizen OS, we must also be able to generate document files (docx) from EP content. Even if we enabled image resize in EP, the image would still appear full size in docx, thus creating an inconsistent user experience. 

The scope of making this change will become very large very quickly for us. Like @tiblu said, we very much welcome pull requests, but it will be an undefined while, before we ourselves get around to implementing image resize. Unless a large number of users start reporting this as an inconvenience.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by loorm** [comment]
@tiblu @ilmartyrk Any changes in the new EP version regarding image resize?

**Comment by ghost** [comment]
Any update regarding image resizing , the old version it took full width of page but now it takes only  1/4 of the page :

old version of plugin better preview:
![image](https://user-images.githubusercontent.com/63293681/140589344-026fcab0-fbcc-4757-a8d4-fc6ab2cd12ff.png)

the new version:
![image](https://user-images.githubusercontent.com/63293681/140589390-ad69edad-883f-45a8-ad20-7328ba8d3c6f.png)

I preferer the old version

**Comment by loorm** [comment]
Tagging @anettlinno. Please see most recent community input above.

**Comment by anettlinno** [comment]
Triage 52.  Currently the maximum height of the picture is set on 500 pixels. We will take off the height limit and this should fix this problem. 
Est. dev. time 30 min. Sending to development.

The limit is set inside ace.css and it comes from etherpad core styles. We can add the style update inside plugin stylesheet to override this limit

**Comment by ilmartyrk** [comment]
Removed the height limit from styles, but this initial issue still remains adding resize functionality to images

**Comment by anettlinno** [comment]
Triage 60. Sending this issue back to In Prep to wait for the decision if we will continue using EP or we change to some other text editor platform. This decision is waiting behind the redesign project.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk seems this may now be relevant again (redesign is done and we still use etherpad), but putting in 'later' for now

**Comment by rhagstrand** [comment]
Ability to resize images would be great!
